name: Deploy React to EC2 (Nginx)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          ssh-keyscan -H your-ec2-ip >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-60-85-0.eu-north-1.compute.amazonaws.com << 'EOF'
            cd ~/NoRunnerReact
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
          EOF
